# Generated by Django 5.1.2 on 2024-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=80000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
