# Generated by Django 5.1.2 on 2024-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_is_dom_content_alter_note_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='prompt',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
